### ISSUE TITLE
PRACTICA "TABLAS DE VERDAD"

### ISSUE THREAD

**Issue by 23620031** [SistemasTecTlaxiaco/actividad-8-practica-de-tablas-de-verdad-equipo-isaias-paola-ariadna-arisbeth#1]
[matematicas discretas practica 2 equipo de isaias  brayan.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-de-tablas-de-verdad-equipo-isaias-paola-ariadna-arisbeth/files/13221645/matematicas.discretas.practica.2.equipo.de.isaias.brayan.pdf)

**Comment by bibiana-m** [comment]
Portadas: 25%
Procedimientos: 25%
Figuras e ilustraciones: 25%
Resultado y conclusiones: 25%

Calificación: 100% / 10 * 20 = 20

Comentario: Gran trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
